services:
  - type: web
    name: science-experiment-advisor
    env: python
    plan: free
    branch: main
    buildCommand: cd chatbot/chatbottttt && pip install -r requirements.txt
    startCommand: cd chatbot/chatbottttt && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
    autoDeploy: true
